name: Python CI

on:
  push:
    branches:
      - main
      - task-1
      - task-2
      - task-3
      - task-4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Flake8
      run: |
        flake8 .

    - name: Run Tests
      run: |
        pytest